# Copyright 2004-2010 OpenERP SA
# Copyright 2014-2018 Tecnativa - Pedro M. Baeza
# Copyright 2015 Domatix
# Copyright 2016-2018 Tecnativa - Carlos Dauden
# Copyright 2017 Tecnativa - Vicent Cubells
# Copyright 2016-2017 LasLabs Inc.
# Copyright 2018-2019 ACSONE SA/NV
# Copyright 2020-2021 Tecnativa - Pedro M. Baeza
# Copyright 2020 Tecnativa - Víctor Martínez
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    "name": "Recurring - Contracts Management",
    "version": "18.0.1.4.5",
    "category": "Contract Management",
    "license": "AGPL-3",
    "author": "Tecnativa, ACSONE SA/NV, Odoo Community Association (OCA)",
    "website": "https://github.com/OCA/contract",
    "depends": ["base", "account", "product", "portal", "stock", "account_followup", "mail"],
    "development_status": "Production/Stable",
    "data": [
        "security/groups.xml",
        "security/contract_inventory_rules.xml",
        "data/nameday_cron.xml",
        "data/mail_template_nameday.xml",
        "security/account_followup_security.xml",
        "data/account_followup_actions.xml",
        "data/usage_pattern_cron.xml",
        "data/mail_template_hours_warning.xml",
        "views/account_followup_views.xml",
        "views/contract_inventory_menu.xml",
        "security/contract_tag.xml",
        "security/ir.model.access.csv",
        "security/product_pairing_security.xml",
        "views/res_users_views.xml",
        "wizards/contract_inventory_bulk_return_wizard_view.xml",
        "wizards/contract_inventory_create_rental_wizard_view.xml",
        "security/contract_security.xml",
        "security/contract_terminate_reason.xml",
        "security/contract_inventory.xml",
        "security/contract_mobile_service.xml",
        "security/contract_mobile_invoice.xml",
        "wizards/contract_inventory_line_export_view.xml",
        "wizards/contract_inventory_import_view.xml",
        "report/report_contract.xml",
        "report/contract_views.xml",
        "report/contract_inventory_line_report.xml",
        "report/contract_inventory_line_report_action.xml",
        "views/contract_inventory_line_views.xml",
        "data/contract_cron.xml",
        "data/contract_renew_cron.xml",
        "data/commitment_cron.xml",
        "data/mail_template.xml",
        "data/mail_template_commitment_1month.xml",
        "data/mail_template_commitment_2month.xml",
        "data/template_mail_notification.xml",
        "data/mail_message_subtype.xml",
        "data/ir_ui_menu.xml",
        "wizards/contract_line_wizard.xml",
        "wizards/contract_manually_create_invoice.xml",
        "wizards/contract_contract_terminate.xml",
        "wizards/contract_mobile_invoice_import.xml",
        "wizards/contract_date_update_wizard_view.xml",
        "wizards/stock_location_select_view.xml",
        "views/sale_views.xml",
        "views/contract_tag.xml",
        "views/abstract_contract_line.xml",
        "views/contract.xml",
        "views/contract_line.xml",
        "views/contract_template.xml",
        "views/contract_template_line.xml",
        "views/res_partner_view.xml",
        "views/res_config_settings.xml",
        "views/contract_terminate_reason.xml",
        "views/mobile_invoice_settings_views.xml",
        "views/contract_portal_templates.xml",
        "views/contract_inventory.xml",
        "views/contract_line_inventory.xml",
        'views/contract_mobile_service.xml',
        'views/contract_mobile_invoice_views.xml',
        'views/supplier_invoice_processor_views.xml',
        'views/product_pairing_rule_views.xml',
        'views/pairing_ignore_rule_views.xml',
        'views/supplier_invoice_line_pairing_views.xml',
        'views/product_template_view.xml',
        'wizards/product_pairing_wizard_views.xml',
        'wizards/supplier_invoice_regenerate_wizard_view.xml',
        'views/contract_menu.xml',
        'data/contract_sequence.xml',
        'data/supplier_invoice_processor_sequence.xml',
        'data/supplier_invoice_processor_alias.xml',
        'data/product_quantity_alert_cron.xml',
        'security/stock_rules.xml',
        'views/account_move_stock_view.xml',
        'views/account_report_inherit.xml',
    ],
    "demo": [
        "data/contract_inventory_demo.xml",
    ],
    "assets": {
        "web.assets_frontend": ["contract/static/src/scss/frontend.scss"],
        "web.assets_tests": ["contract/static/src/js/contract_portal_tour.esm.js"],
    },
    "installable": True,
}
